#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'py-chester-pkg','console_scripts','light_controller'
__requires__ = 'py-chester-pkg'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('py-chester-pkg', 'console_scripts', 'light_controller')()
    )
